# Generated by Django 4.2.30 on 2026-04-10 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GRN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('received', 'Received'), ('inspected', 'Inspected'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Receiving notes and remarks')),
                ('quality_check_notes', models.TextField(blank=True, help_text='Quality inspection remarks')),
                ('received_by', models.CharField(max_length=200)),
                ('inspected_by', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GRNItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.IntegerField(default=0)),
                ('quantity_accepted', models.IntegerField(default=0)),
                ('quantity_rejected', models.IntegerField(default=0)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged'), ('partial', 'Partially Damaged'), ('shortlisted', 'Short Listed')], default='good', max_length=20)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='grn.grn')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
