# Generated by Django 4.2.30 on 2026-04-10 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grn', '0001_initial'),
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnitem',
            name='po_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grn_items', to='purchase_order.purchaseorderitem'),
        ),
        migrations.AddField(
            model_name='grn',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grns', to='purchase_order.purchaseorder'),
        ),
    ]
