# Generated by Django 4.2.30 on 2026-04-10 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotation', '0002_alter_quotation_inquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProformaInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('converted', 'Converted to Invoice'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=50)),
                ('customer_company', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(default='Proforma Invoice', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed'), ('percent', 'Percentage')], default='fixed', max_length=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True, help_text='Additional notes for the proforma invoice')),
                ('terms', models.TextField(blank=True, help_text='Terms and conditions')),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='Admin', max_length=200)),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proforma_invoice', to='quotation.quotation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProformaInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proforma_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proforma_invoice.proformainvoice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
